POST http://localhost:4000/lps
Content-Type: application/json

   {
    "title": "thirdTag",
    "description": "aaaaaaaaaaaa",
    "artist": "first",
    "release_year": 4567,
    "picture":
      "aaaaaaaaaaaaaaaa",
    "label": "aaaaaaa",
    "category": 1,
    "tags": [1, 2]
  }