POST http://localhost:4000/lps
Content-Type: application/json

   {
    "title": "Third",
    "description": "aaaaaaaaaaaa",
    "artist": "Artist",
    "release_year": 4567,
    "picture":
      "aaaaaaaaaaaaaaaa",
    "label": "aaaaaaa",
    "createdAt": "aaaaaaaaaaaaaaa"
  }